-- Treesitter capture highlights, see `:h treesitter-highlight`.
local M = {}

---@param c lighter.Palette
function M.get_hl(c)
  -- stylua: ignore
  return {
    ["@variable"]                      = { fg = c.fg },
    ["@variable.builtin"]              = { link = "Constant" }, -- this, self
    ["@variable.parameter"]            = { fg = c.fg },
    ["@variable.parameter.builtin"]    = { fg = c.fg },
    ["@variable.member"]               = { fg = c.fg },
    ["@constant"]                      = { link = "Constant" },
    ["@constant.macro"]                = { link = "Constant" },
    ["@constant.builtin"]              = { link = "Constant" },
    ["@module"]                        = { fg = c.fg },
    ["@module.builtin"]                = { link = "Special" },
    ["@label"]                         = { link = "Structure" },
    ["@string"]                        = { link = "String" },
    ["@string.documentation"]          = { link = "Comment" },
    ["@string.regexp"]                 = { link = "String" },
    ["@string.escape"]                 = { link = "Special" },
    ["@string.special"]                = { link = "Special" },
    ["@string.special.symbol"]         = { link = "Special" },
    ["@string.special.path"]           = { link = "Special" },
    ["@string.special.url"]            = { link = "Underlined" },
    ["@character"]                     = { link = "Character" },
    ["@character.special"]             = { fg = c.special },
    ["@boolean"]                       = { link = "Boolean" },
    ["@number"]                        = { link = "Number" },
    ["@number.float"]                  = { link = "Number" },
    ["@type"]                          = { link = "Type" },
    ["@type.builtin"]                  = { link = "Type" },
    ["@type.definition"]               = { fg = c.fg },
    ["@attribute"]                     = { link = "Keyword" },
    ["@attribute.builtin"]             = { link = "Keyword" },
    ["@property"]                      = { fg = c.fg },
    ["@function"]                      = { link = "Function" },
    ["@function.builtin"]              = { link = "Function" },
    ["@function.call"]                 = { link = "Function" },
    ["@function.macro"]                = { link = "Macro" },
    ["@function.method"]               = { link = "Function" },
    ["@function.method.call"]          = { link = "Function" },
    ["@constructor"]                   = { fg = c.fg },
    ["@operator"]                      = { link = "Operator" },
    ["@keyword"]                       = { link = "Keyword" },
    ["@keyword.coroutine"]             = { link = "Keyword" },
    ["@keyword.function"]              = { link = "Keyword" },
    ["@keyword.operator"]              = { link = "Operator" },
    ["@keyword.import"]                = { link = "Include" },
    ["@keyword.type"]                  = { link = "Keyword" },
    ["@keyword.modifier"]              = { link = "Keyword" },
    ["@keyword.repeat"]                = { link = "Repeat" },
    ["@keyword.return"]                = { fg = c.emphasis },
    ["@keyword.debug"]                 = { link = "Keyword" },
    ["@keyword.exception"]             = { link = "Exception" },
    ["@keyword.conditional"]           = { link = "Conditional" },
    ["@keyword.conditional.ternary"]   = { link = "Conditional" },
    ["@keyword.directive"]             = { link = "Keyword" },
    ["@keyword.directive.define"]      = { link = "Keyword" },
    ["@punctuation"]                   = { link = "Keyword" },
    ["@punctuation.delimiter"]         = { link = "Delimiter" },
    ["@punctuation.bracket"]           = { fg = c.fg },
    ["@punctuation.special"]           = { fg = c.fg },
    ["@comment"]                       = { link = "Comment" },
    ["@comment.documentation"]         = { link = "Comment" },
    ["@comment.error"]                 = { fg = c.danger },
    ["@comment.warning"]               = { fg = c.warning },
    ["@comment.todo"]                  = { fg = c.info },
    ["@comment.note"]                  = { fg = c.emphasis },
    ["@markup.strong"]                 = { bold = true },
    ["@markup.italic"]                 = { italic = true },
    ["@markup.strikethrough"]          = { fg = c.danger, strikethrough = true },
    ["@markup.underline"]              = { underline = true },
    ["@markup.heading"]                = { fg = c.emphasis, bold = true },
    ["@markup.heading.gitcommit"]      = { fg = c.fg },
    ["@markup.heading.1.markdown"]     = { link = "@markup.heading" },
    ["@markup.heading.2.markdown"]     = { link = "@markup.heading" },
    ["@markup.heading.3.markdown"]     = { link = "@markup.heading" },
    ["@markup.heading.4.markdown"]     = { link = "@markup.heading" },
    ["@markup.heading.5.markdown"]     = { link = "@markup.heading" },
    ["@markup.heading.6.markdown"]     = { link = "@markup.heading" },
    ["@markup.quote"]                  = { link = "Comment" },
    ["@markup.math"]                   = { link = "Special" },
    ["@markup.link"]                   = { fg = c.emphasis, underline = true },
    ["@markup.link.label"]             = { fg = c.emphasis, underline = false },
    ["@markup.link.url"]               = { fg = c.info, underline = true },
    ["@markup.raw"]                    = { fg = c.const },
    ["@markup.raw.block"]              = { fg = c.const },
    ["@markup.list"]                   = { fg = c.emphasis },
    ["@markup.list.checked"]           = { fg = c.success },
    ["@markup.list.unchecked"]         = { fg = c.danger },
    ["@diff.plus"]                     = { link = "DiffAdd" },
    ["@diff.minus"]                    = { link = "DiffDelete" },
    ["@diff.delta"]                    = { link = "DiffChange" },
    ["@tag"]                           = { link = "Keyword" },
    ["@tag.builtin"]                   = { fg = c.fg },
    ["@tag.delimiter"]                 = { link = "Keyword" },
    ["@tag.attribute"]                 = { link = "Keyword" },
  }
end

return M
